


const products = [
    {
      "ID": 66,
      "Type": "simple",
      "SKU": "",
      "Name": "Divi Engine String Bag (Big Logo)",
      "Published": 1,
      "Is featured?": 0,
      "Visibility in catalog": "visible",
      "Short description": "This fashionable string bag is made of 100% cotton. It is the perfect size for carrying your everyday essentials.",
      "Description": "",
      "Date sale price starts": "",
      "Date sale price ends": "",
      "Tax status": "taxable",
      "Tax class": "",
      "In stock?": 1,
      "Stock": "",
      "Low stock amount": "",
      "Backorders allowed?": 0,
      "Sold individually?": 0,
      "Weight (kg)": "",
      "Length (cm)": "",
      "Width (cm)": "",
      "Height (cm)": "",
      "Allow customer reviews?": 1,
      "Purchase note": "",
      "Sale price": "",
      "Regular price": 19.99,
      "Categories": "Accessories",
      "Tags": "",
      "Shipping class": "",
      "Images": "https://ajax-filters-bc.diviengine.com/sampledata/images/Bag1.jpg, https://ajax-filters-bc.diviengine.com/sampledata/images/Bag1-1.jpg, https://ajax-filters-bc.diviengine.com/sampledata/images/Bag1-2.jpg",
      "Download limit": "",
      "Download expiry days": "",
      "Parent": "",
      "Grouped products": "",
      "Upsells": "",
      "Cross-sells": "",
      "External URL": "",
      "Button text": "",
      "Position": 0,
      "Attribute 1 name": "Brand",
      "Attribute 1 value(s)": "Divi Engine",
      "Attribute 1 visible": 1,
      "Attribute 1 global": 1,
      "Meta: _et_pb_post_hide_nav": "default",
      "Meta: _et_pb_page_layout": "et_right_sidebar",
      "Meta: _et_pb_side_nav": "off",
      "Meta: _et_pb_use_builder": "",
      "Meta: _et_pb_first_image": "",
      "Meta: _et_pb_truncate_post": "",
      "Meta: _et_pb_truncate_post_date": "",
      "Meta: _et_pb_old_content": "",
      "Attribute 1 default": "",
      "Attribute 2 name": "",
      "Attribute 2 value(s)": "",
      "Attribute 2 visible": "",
      "Attribute 2 global": "",
      "Attribute 2 default": "",
      "Attribute 3 name": "",
      "Attribute 3 value(s)": "",
      "Attribute 3 visible": "",
      "Attribute 3 global": "",
      "Attribute 3 default": ""
    },
    {
      "ID": 70,
      "Type": "simple",
      "SKU": "",
      "Name": "Divi Engine String Bag (Small Logos)",
      "Published": 1,
      "Is featured?": 0,
      "Visibility in catalog": "visible",
      "Short description": "This fashionable string bag is made of 100% cotton. It is the perfect size for carrying your everyday essentials.",
      "Description": "",
      "Date sale price starts": "",
      "Date sale price ends": "",
      "Tax status": "taxable",
      "Tax class": "",
      "In stock?": 1,
      "Stock": "",
      "Low stock amount": "",
      "Backorders allowed?": 0,
      "Sold individually?": 0,
      "Weight (kg)": "",
      "Length (cm)": "",
      "Width (cm)": "",
      "Height (cm)": "",
      "Allow customer reviews?": 1,
      "Purchase note": "",
      "Sale price": "",
      "Regular price": 19.99,
      "Categories": "Accessories",
      "Tags": "",
      "Shipping class": "",
      "Images": "https://ajax-filters-bc.diviengine.com/sampledata/images/Bag2.jpg, https://ajax-filters-bc.diviengine.com/sampledata/images/Bag2-1.jpg, https://ajax-filters-bc.diviengine.com/sampledata/images/Bag2-2.jpg",
      "Download limit": "",
      "Download expiry days": "",
      "Parent": "",
      "Grouped products": "",
      "Upsells": "",
      "Cross-sells": "",
      "External URL": "",
      "Button text": "",
      "Position": 0,
      "Attribute 1 name": "Brand",
      "Attribute 1 value(s)": "Divi Engine",
      "Attribute 1 visible": 1,
      "Attribute 1 global": 1,
      "Meta: _et_pb_post_hide_nav": "default",
      "Meta: _et_pb_page_layout": "et_right_sidebar",
      "Meta: _et_pb_side_nav": "off",
      "Meta: _et_pb_use_builder": "",
      "Meta: _et_pb_first_image": "",
      "Meta: _et_pb_truncate_post": "",
      "Meta: _et_pb_truncate_post_date": "",
      "Meta: _et_pb_old_content": "",
      "Attribute 1 default": "",
      "Attribute 2 name": "",
      "Attribute 2 value(s)": "",
      "Attribute 2 visible": "",
      "Attribute 2 global": "",
      "Attribute 2 default": "",
      "Attribute 3 name": "",
      "Attribute 3 value(s)": "",
      "Attribute 3 visible": "",
      "Attribute 3 global": "",
      "Attribute 3 default": ""
    },
    {
      "ID": 74,
      "Type": "variable",
      "SKU": "",
      "Name": "Brand Buttons",
      "Published": 1,
      "Is featured?": 0,
      "Visibility in catalog": "visible",
      "Short description": "Represent your favorite CMS, eCommerce Platform, Website Builder, or Plugin Company in style with a cool pin.",
      "Description": "",
      "Date sale price starts": "",
      "Date sale price ends": "",
      "Tax status": "taxable",
      "Tax class": "",
      "In stock?": 1,
      "Stock": "",
      "Low stock amount": "",
      "Backorders allowed?": 0,
      "Sold individually?": 0,
      "Weight (kg)": "",
      "Length (cm)": "",
      "Width (cm)": "",
      "Height (cm)": "",
      "Allow customer reviews?": 1,
      "Purchase note": "",
      "Sale price": "",
      "Regular price": "",
      "Categories": "Accessories",
      "Tags": "",
      "Shipping class": "",
      "Images": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-4.jpg",
      "Download limit": "",
      "Download expiry days": "",
      "Parent": "",
      "Grouped products": "",
      "Upsells": "",
      "Cross-sells": "",
      "External URL": "",
      "Button text": "",
      "Position": 0,
      "Attribute 1 name": "Brand",
      "Attribute 1 value(s)": "Divi, Divi Engine, WooCommerce, WordPress",
      "Attribute 1 visible": 1,
      "Attribute 1 global": 1,
      "Meta: _et_pb_post_hide_nav": "default",
      "Meta: _et_pb_page_layout": "et_right_sidebar",
      "Meta: _et_pb_side_nav": "off",
      "Meta: _et_pb_use_builder": "",
      "Meta: _et_pb_first_image": "",
      "Meta: _et_pb_truncate_post": "",
      "Meta: _et_pb_truncate_post_date": "",
      "Meta: _et_pb_old_content": "",
      "Attribute 1 default": "Divi Engine",
      "Attribute 2 name": "",
      "Attribute 2 value(s)": "",
      "Attribute 2 visible": "",
      "Attribute 2 global": "",
      "Attribute 2 default": "",
      "Attribute 3 name": "",
      "Attribute 3 value(s)": "",
      "Attribute 3 visible": "",
      "Attribute 3 global": "",
      "Attribute 3 default": ""
    },
    {
      "ID": 75,
      "Type": "variation",
      "SKU": "",
      "Name": "Brand Buttons - Divi",
      "Published": 1,
      "Is featured?": 0,
      "Visibility in catalog": "visible",
      "Short description": "",
      "Description": "Rep your love for Divi!",
      "Date sale price starts": "",
      "Date sale price ends": "",
      "Tax status": "taxable",
      "Tax class": "parent",
      "In stock?": 1,
      "Stock": "",
      "Low stock amount": "",
      "Backorders allowed?": 0,
      "Sold individually?": 0,
      "Weight (kg)": "",
      "Length (cm)": "",
      "Width (cm)": "",
      "Height (cm)": "",
      "Allow customer reviews?": 0,
      "Purchase note": "",
      "Sale price": "",
      "Regular price": 9.99,
      "Categories": "",
      "Tags": "",
      "Shipping class": "",
      "Images": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-1.jpg",
      "Download limit": "",
      "Download expiry days": "",
      "Parent": "id:74",
      "Grouped products": "",
      "Upsells": "",
      "Cross-sells": "",
      "External URL": "",
      "Button text": "",
      "Position": 1,
      "Attribute 1 name": "Brand",
      "Attribute 1 value(s)": "Divi",
      "Attribute 1 visible": "",
      "Attribute 1 global": 1,
      "Meta: _et_pb_post_hide_nav": "",
      "Meta: _et_pb_page_layout": "",
      "Meta: _et_pb_side_nav": "",
      "Meta: _et_pb_use_builder": "",
      "Meta: _et_pb_first_image": "",
      "Meta: _et_pb_truncate_post": "",
      "Meta: _et_pb_truncate_post_date": "",
      "Meta: _et_pb_old_content": "",
      "Attribute 1 default": "",
      "Attribute 2 name": "",
      "Attribute 2 value(s)": "",
      "Attribute 2 visible": "",
      "Attribute 2 global": "",
      "Attribute 2 default": "",
      "Attribute 3 name": "",
      "Attribute 3 value(s)": "",
      "Attribute 3 visible": "",
      "Attribute 3 global": "",
      "Attribute 3 default": ""
    },
    {
      "ID": 76,
      "Type": "variation",
      "SKU": "",
      "Name": "Brand Buttons - Divi Engine",
      "Published": 1,
      "Is featured?": 0,
      "Visibility in catalog": "visible",
      "Short description": "",
      "Description": "Rep your love for Divi Engine!",
      "Date sale price starts": "",
      "Date sale price ends": "",
      "Tax status": "taxable",
      "Tax class": "parent",
      "In stock?": 1,
      "Stock": "",
      "Low stock amount": "",
      "Backorders allowed?": 0,
      "Sold individually?": 0,
      "Weight (kg)": "",
      "Length (cm)": "",
      "Width (cm)": "",
      "Height (cm)": "",
      "Allow customer reviews?": 0,
      "Purchase note": "",
      "Sale price": "",
      "Regular price": 9.99,
      "Categories": "",
      "Tags": "",
      "Shipping class": "",
      "Images": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-4.jpg",
      "Download limit": "",
      "Download expiry days": "",
      "Parent": "id:74",
      "Grouped products": "",
      "Upsells": "",
      "Cross-sells": "",
      "External URL": "",
      "Button text": "",
      "Position": 2,
      "Attribute 1 name": "Brand",
      "Attribute 1 value(s)": "Divi Engine",
      "Attribute 1 visible": "",
      "Attribute 1 global": 1,
      "Meta: _et_pb_post_hide_nav": "",
      "Meta: _et_pb_page_layout": "",
      "Meta: _et_pb_side_nav": "",
      "Meta: _et_pb_use_builder": "",
      "Meta: _et_pb_first_image": "",
      "Meta: _et_pb_truncate_post": "",
      "Meta: _et_pb_truncate_post_date": "",
      "Meta: _et_pb_old_content": "",
      "Attribute 1 default": "",
      "Attribute 2 name": "",
      "Attribute 2 value(s)": "",
      "Attribute 2 visible": "",
      "Attribute 2 global": "",
      "Attribute 2 default": "",
      "Attribute 3 name": "",
      "Attribute 3 value(s)": "",
      "Attribute 3 visible": "",
      "Attribute 3 global": "",
      "Attribute 3 default": ""
    },
    {
      "ID": 77,
      "Type": "variation",
      "SKU": "",
      "Name": "Brand Buttons - WooCommerce",
      "Published": 1,
      "Is featured?": 0,
      "Visibility in catalog": "visible",
      "Short description": "",
      "Description": "Rep your love for WooCommerce!",
      "Date sale price starts": "",
      "Date sale price ends": "",
      "Tax status": "taxable",
      "Tax class": "parent",
      "In stock?": 1,
      "Stock": "",
      "Low stock amount": "",
      "Backorders allowed?": 0,
      "Sold individually?": 0,
      "Weight (kg)": "",
      "Length (cm)": "",
      "Width (cm)": "",
      "Height (cm)": "",
      "Allow customer reviews?": 0,
      "Purchase note": "",
      "Sale price": "",
      "Regular price": 9.99,
      "Categories": "",
      "Tags": "",
      "Shipping class": "",
      "Images": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-2.jpg",
      "Download limit": "",
      "Download expiry days": "",
      "Parent": "id:74",
      "Grouped products": "",
      "Upsells": "",
      "Cross-sells": "",
      "External URL": "",
      "Button text": "",
      "Position": 3,
      "Attribute 1 name": "Brand",
      "Attribute 1 value(s)": "WooCommerce",
      "Attribute 1 visible": "",
      "Attribute 1 global": 1,
      "Meta: _et_pb_post_hide_nav": "",
      "Meta: _et_pb_page_layout": "",
      "Meta: _et_pb_side_nav": "",
      "Meta: _et_pb_use_builder": "",
      "Meta: _et_pb_first_image": "",
      "Meta: _et_pb_truncate_post": "",
      "Meta: _et_pb_truncate_post_date": "",
      "Meta: _et_pb_old_content": "",
      "Attribute 1 default": "",
      "Attribute 2 name": "",
      "Attribute 2 value(s)": "",
      "Attribute 2 visible": "",
      "Attribute 2 global": "",
      "Attribute 2 default": "",
      "Attribute 3 name": "",
      "Attribute 3 value(s)": "",
      "Attribute 3 visible": "",
      "Attribute 3 global": "",
      "Attribute 3 default": ""
    },
    {
      "ID": 78,
      "Type": "variation",
      "SKU": "",
      "Name": "Brand Buttons - WordPress",
      "Published": 1,
      "Is featured?": 0,
      "Visibility in catalog": "visible",
      "Short description": "",
      "Description": "Rep your love for WordPress!",
      "Date sale price starts": "",
      "Date sale price ends": "",
      "Tax status": "taxable",
      "Tax class": "parent",
      "In stock?": 1,
      "Stock": "",
      "Low stock amount": "",
      "Backorders allowed?": 0,
      "Sold individually?": 0,
      "Weight (kg)": "",
      "Length (cm)": "",
      "Width (cm)": "",
      "Height (cm)": "",
      "Allow customer reviews?": 0,
      "Purchase note": "",
      "Sale price": "",
      "Regular price": 9.99,
      "Categories": "",
      "Tags": "",
      "Shipping class": "",
      "Images": "https://ajax-filters-bc.diviengine.com/sampledata/images/DE-Pins-3.jpg",
      "Download limit": "",
      "Download expiry days": "",
      "Parent": "id:74",
      "Grouped products": "",
      "Upsells": "",
      "Cross-sells": "",
      "External URL": "",
      "Button text": "",
      "Position": 4,
      "Attribute 1 name": "Brand",
      "Attribute 1 value(s)": "WordPress",
      "Attribute 1 visible": "",
      "Attribute 1 global": 1,
      "Meta: _et_pb_post_hide_nav": "",
      "Meta: _et_pb_page_layout": "",
      "Meta: _et_pb_side_nav": "",
      "Meta: _et_pb_use_builder": "",
      "Meta: _et_pb_first_image": "",
      "Meta: _et_pb_truncate_post": "",
      "Meta: _et_pb_truncate_post_date": "",
      "Meta: _et_pb_old_content": "",
      "Attribute 1 default": "",
      "Attribute 2 name": "",
      "Attribute 2 value(s)": "",
      "Attribute 2 visible": "",
      "Attribute 2 global": "",
      "Attribute 2 default": "",
      "Attribute 3 name": "",
      "Attribute 3 value(s)": "",
      "Attribute 3 visible": "",
      "Attribute 3 global": "",
      "Attribute 3 default": ""
    },
    {
      "ID": 83,
      "Type": "simple",
      "SKU": "",
      "Name": "Lanyard",
      "Published": 1,
      "Is featured?": 0,
      "Visibility in catalog": "visible",
      "Short description": "Stop losing your important access keys with a lanyard that is ALMOST as reliable as Divi Engine plugins!",
      "Description": "",
      "Date sale price starts": "",
      "Date sale price ends": "",
      "Tax status": "taxable",
      "Tax class": "",
      "In stock?": 1,
      "Stock": "",
      "Low stock amount": "",
      "Backorders allowed?": 0,
      "Sold individually?": 0,
      "Weight (kg)": "",
      "Length (cm)": "",
      "Width (cm)": "",
      "Height (cm)": "",
      "Allow customer reviews?": 1,
      "Purchase note": "",
      "Sale price": 7.99,
      "Regular price": 9.99,
      "Categories": "Accessories",
      "Tags": "",
      "Shipping class": "",
      "Images": "https://ajax-filters-bc.diviengine.com/sampledata/images/Lanyard1.jpg",
      "Download limit": "",
      "Download expiry days": "",
      "Parent": "",
      "Grouped products": "",
      "Upsells": "",
      "Cross-sells": "",
      "External URL": "",
      "Button text": "",
      "Position": 0,
      "Attribute 1 name": "Brand",
      "Attribute 1 value(s)": "Divi Engine",
      "Attribute 1 visible": 1,
      "Attribute 1 global": 1,
      "Meta: _et_pb_post_hide_nav": "default",
      "Meta: _et_pb_page_layout": "et_right_sidebar",
      "Meta: _et_pb_side_nav": "off",
      "Meta: _et_pb_use_builder": "",
      "Meta: _et_pb_first_image": "",
      "Meta: _et_pb_truncate_post": "",
      "Meta: _et_pb_truncate_post_date": "",
      "Meta: _et_pb_old_content": "",
      "Attribute 1 default": "",
      "Attribute 2 name": "",
      "Attribute 2 value(s)": "",
      "Attribute 2 visible": "",
      "Attribute 2 global": "",
      "Attribute 2 default": "",
      "Attribute 3 name": "",
      "Attribute 3 value(s)": "",
      "Attribute 3 visible": "",
      "Attribute 3 global": "",
      "Attribute 3 default": ""
    }
  ]




let img = []



  export const data = ()=>{
   

}

export const imgdata = products